@extends('layouts.executive-center')
@section('title', 'Business Attention')
@section('page_title', 'Business Attention')
@section('meta_description', 'Priority issues requiring management awareness and coordinated action.')
@section('page_description', 'Priority issues requiring management awareness and coordinated action.')

@section('header_actions')
<div class="flex min-w-0 flex-col gap-3 xl:items-end">
    <p id="attentionFilterSummary" class="text-xs font-extrabold text-executive-ink">{{ collect($states)->firstWhere('key', $filters['state'])['label'] ?? 'Open issues' }} · {{ collect($divisions)->firstWhere('key', $filters['division'])['label'] ?? 'All divisions' }}</p>
    <div class="flex flex-col gap-2 sm:flex-row">
        <select id="attentionState" class="h-10 rounded-xl border border-executive-line bg-white px-3 text-xs font-bold text-executive-ink outline-none focus:border-executive-primary">@foreach($states as $option)<option value="{{ $option['key'] }}" @selected($filters['state']===$option['key'])>{{ $option['label'] }}</option>@endforeach</select>
        <select id="attentionDivision" class="h-10 rounded-xl border border-executive-line bg-white px-3 text-xs font-bold text-executive-ink outline-none focus:border-executive-primary">@foreach($divisions as $option)<option value="{{ $option['key'] }}" @selected($filters['division']===$option['key'])>{{ $option['label'] }}</option>@endforeach</select>
        <input id="attentionPeriod" type="month" value="{{ $filters['period'] }}" class="h-10 min-w-[152px] rounded-xl border border-executive-line bg-white px-3 text-xs font-bold text-executive-ink outline-none focus:border-executive-primary">
    </div>
</div>
@endsection

@push('styles')
<style>
.executive-main-card{overflow:visible!important;border:0!important;background:transparent!important;box-shadow:none!important}.executive-page-header{border:1px solid #E5E1EE!important;border-radius:1.25rem!important;background:#fff!important;box-shadow:0 16px 45px rgba(31,27,46,.07)!important}.executive-content{padding:0!important}
#attentionPage{padding-top:1.25rem!important}
#attentionDetail>p:first-child{font-size:.875rem;font-weight:800;letter-spacing:0;text-transform:none;color:#2D2938}
#attentionStats{margin-top:0!important}
.attention-row:has(.bg-rose-50){border-color:#FFE4E6;background:rgba(255,241,242,.4)}
.attention-row:has(.bg-amber-50){border-color:#FEF3C7;background:rgba(255,251,235,.4)}
.attention-row:has(.bg-violet-50){border-color:#EDE9FE;background:rgba(245,243,255,.4)}
.attention-row:has(.bg-emerald-50){border-color:#D1FAE5;background:rgba(236,253,245,.4)}
.attention-row[aria-selected="true"]{border-color:#DDD6FE;background:rgba(245,243,255,.7)}
@media(max-width:639px){.executive-page-header{border-radius:1rem!important}#attentionPage{padding-top:1rem!important}}
@media print{#attentionPage{padding-top:0!important}}
</style>
@endpush

@section('content')
@php($initialAttentionData = ['issues' => $issues, 'selectedIssue' => $selectedIssue, 'summary' => $summary, 'hasAvailableKpi' => $hasAvailableKpi, 'period' => $period, 'filters' => $filters])
<div id="attentionPage" data-url="{{ route('executive-center.business-attention.data') }}" class="relative min-w-0 space-y-5" aria-busy="false">
    <div id="attentionLoading" class="absolute inset-0 z-20 hidden min-h-[360px] items-start justify-center rounded-2xl bg-white/90 pt-20 backdrop-blur-[1px]" role="status" aria-live="polite"><div class="text-center"><i data-lucide="loader-circle" class="mx-auto h-7 w-7 animate-spin text-executive-primary" aria-hidden="true"></i><p id="attentionLoadingTitle" class="mt-4 text-sm font-extrabold text-executive-ink"></p><p class="mt-1 text-xs text-executive-muted">FlexOps is consolidating the latest KPI and business performance data.</p></div></div>
    <div id="attentionError" class="hidden rounded-xl border border-rose-100 bg-rose-50/50 p-4 text-xs text-rose-700" role="alert">Unable to update the data. Please try again. The previously loaded information is still displayed.</div>
    <section id="attentionStats" class="grid grid-cols-2 gap-4 xl:grid-cols-4"></section>
    <div class="grid min-w-0 grid-cols-1 gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]">
        <section class="min-w-0 rounded-2xl border border-executive-line bg-white p-5 shadow-panel"><header><h2 class="text-sm font-extrabold text-executive-ink">Priority Queue</h2><p class="mt-1 text-[11px] font-medium text-executive-muted">Sorted by severity and business impact.</p></header><div id="attentionQueue" class="mt-5 space-y-3"></div></section>
        <aside id="attentionDetail" class="min-w-0 self-start rounded-2xl border border-executive-line bg-white p-5 shadow-panel xl:sticky xl:top-28"></aside>
    </div>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const page=document.getElementById('attentionPage'),period=document.getElementById('attentionPeriod'),division=document.getElementById('attentionDivision'),state=document.getElementById('attentionState'),loading=document.getElementById('attentionLoading'),error=document.getElementById('attentionError');let controller=null,currentData={{ Illuminate\Support\Js::from($initialAttentionData) }};
 window.renderLucideIcons?.(page);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const badge=(label,tone)=>`<span class="inline-flex rounded-md px-2.5 py-1 text-[9px] font-extrabold uppercase tracking-[.06em] ring-1 ring-inset ${tone}">${esc(label)}</span>`;
 const tones={critical:'bg-rose-50 text-rose-700 ring-rose-200',high:'bg-amber-50 text-amber-700 ring-amber-200',medium:'bg-violet-50 text-executive-primary ring-violet-200',resolved:'bg-emerald-50 text-emerald-700 ring-emerald-200'};
 const fmt=v=>v?new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
 function detail(item){const el=document.getElementById('attentionDetail');if(!item){el.innerHTML=`<div class="py-10 text-center"><h3 class="text-sm font-extrabold text-executive-ink">${currentData.hasAvailableKpi?'No business attention required':'Not enough business data'}</h3><p class="mt-2 text-xs text-executive-muted">${currentData.hasAvailableKpi?'No active issues were identified for this period and division.':'There is not enough available data to identify business attention items for this period.'}</p></div>`;return}const section=(title,text,extra='')=>text?`<section class="rounded-xl border border-executive-line bg-slate-50/45 p-4"><div class="flex flex-wrap items-center gap-2"><h4 class="text-[10px] font-extrabold uppercase tracking-[.08em] text-executive-primary">${title}</h4>${extra}</div><p class="mt-2 text-xs leading-5 text-executive-muted">${esc(text)}</p></section>`:'';el.innerHTML=`<p class="text-[10px] font-extrabold uppercase tracking-[.1em] text-executive-muted">Selected Issue</p><div class="mt-3 rounded-xl border border-violet-100 bg-violet-50/40 p-4"><div class="flex flex-wrap items-start justify-between gap-2"><h3 class="text-lg font-extrabold text-executive-ink">${esc(item.title)}</h3>${badge(item.severity_label,tones[item.severity]||tones.medium)}</div><p class="mt-3 text-xs font-bold text-executive-ink">${esc(item.metric_summary)}</p></div><div class="mt-3 space-y-3">${section(item.root_cause_type==='confirmed'?'Confirmed Cause':'Likely Root Cause',item.root_cause,item.root_cause_type==='confirmed'?badge('Confirmed by Data','bg-emerald-50 text-emerald-700 ring-emerald-200'):badge('AI Indication','bg-violet-50 text-executive-primary ring-violet-200'))}${section('Business Impact',item.business_impact)}${section(item.recommendation_type,item.recommendation)}${section('Expected Impact',item.expected_impact)}</div><dl class="mt-3 grid grid-cols-2 gap-3 text-[10px]"><div class="rounded-xl border border-executive-line p-3"><dt class="text-executive-muted">Owner</dt><dd class="mt-1 font-extrabold text-executive-ink">${esc(item.owner)}</dd></div><div class="rounded-xl border border-executive-line p-3"><dt class="text-executive-muted">Last Updated</dt><dd class="mt-1 font-extrabold text-executive-ink">${esc(fmt(item.updated_at))}</dd></div><div class="rounded-xl border border-executive-line p-3"><dt class="text-executive-muted">Source</dt><dd class="mt-1 font-extrabold text-executive-ink">${esc(item.source)}</dd></div><div class="rounded-xl border border-executive-line p-3"><dt class="text-executive-muted">State</dt><dd class="mt-1 font-extrabold text-executive-ink">${esc(item.state_label)}</dd></div></dl>`}
 function render(data){currentData=data;const cards=[['Critical',data.summary.critical,'Immediate decision','text-rose-700','bg-rose-50','circle-alert'],['High',data.summary.high,'Action this week','text-amber-700','bg-amber-50','triangle-alert'],['Medium',data.summary.medium,'Monitor closely','text-executive-primary','bg-violet-50','clock-3'],['Resolved',data.summary.resolved,'This month','text-emerald-700','bg-emerald-50','circle-check-big']];const stats=document.getElementById('attentionStats');stats.innerHTML=cards.map(c=>`<article class="rounded-2xl border border-executive-line bg-white p-5 shadow-panel"><div class="flex items-start justify-between gap-3"><p class="text-[11px] font-bold text-executive-muted">${c[0]}</p><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${c[4]} ${c[3]}"><i data-lucide="${c[5]}" class="h-[18px] w-[18px]" aria-hidden="true"></i></span></div><p class="mt-3 text-2xl font-black ${c[3]}">${c[1]}</p><p class="mt-1 text-[10px] font-semibold text-executive-muted">${c[2]}</p></article>`).join('');window.renderLucideIcons?.(stats);const rows=data.issues||[];document.getElementById('attentionQueue').innerHTML=rows.length?rows.map(i=>`<button type="button" data-issue="${esc(i.key)}" class="attention-row block w-full rounded-xl border p-4 text-left transition hover:border-executive-primary/30 hover:bg-violet-50/30 ${data.selectedIssue?.key===i.key?'border-violet-200 bg-violet-50/60':'border-executive-line bg-white'}" aria-selected="${data.selectedIssue?.key===i.key}"><div class="flex flex-wrap items-center gap-2">${badge(i.severity_label,tones[i.severity]||tones.medium)}${badge(i.state_label,'bg-slate-100 text-slate-600 ring-slate-200')}<span class="text-[10px] font-semibold text-executive-muted">${esc(i.division_label)}</span></div><h3 class="mt-3 text-sm font-extrabold text-executive-ink">${esc(i.title)}</h3><p class="mt-1 text-xs text-executive-muted">${esc(i.metric_summary)}</p><span class="mt-3 inline-block text-[10px] font-extrabold text-executive-primary">View detail</span></button>`).join(''):`<div class="p-12 text-center"><p class="text-sm font-extrabold text-executive-ink">No business attention required</p><p class="mt-2 text-xs text-executive-muted">No active issues were identified for this period and division.</p></div>`;document.querySelectorAll('.attention-row').forEach(b=>b.addEventListener('click',()=>{const item=rows.find(i=>i.key===b.dataset.issue);detail(item);document.querySelectorAll('.attention-row').forEach(x=>{x.setAttribute('aria-selected',x===b?'true':'false');x.classList.toggle('bg-violet-50',x===b)});const u=new URL(location.href);u.searchParams.set('issue',b.dataset.issue);history.pushState({},'',u)}));detail(data.selectedIssue);document.getElementById('attentionFilterSummary').textContent=`${state.options[state.selectedIndex].text} · ${division.options[division.selectedIndex].text}`}
 async function load(push=true){controller?.abort();controller=new AbortController();[period,division,state].forEach(x=>x.disabled=true);page.setAttribute('aria-busy','true');error.classList.add('hidden');loading.classList.remove('hidden');loading.classList.add('flex');document.getElementById('attentionLoadingTitle').textContent=`Loading ${new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(period.value+'-01T00:00:00'))} data...`;const q=new URLSearchParams({period:period.value,division:division.value,state:state.value});try{const r=await fetch(`${page.dataset.url}?${q}`,{headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'},signal:controller.signal});const p=await r.json();if(!r.ok||!p.success)throw new Error();render(p.data);if(push)history.pushState({},'',`${location.pathname}?${new URLSearchParams(p.data.filters)}`)}catch(e){if(e.name!=='AbortError')error.classList.remove('hidden')}finally{if(!controller.signal.aborted){[period,division,state].forEach(x=>x.disabled=false);page.setAttribute('aria-busy','false');loading.classList.add('hidden');loading.classList.remove('flex')}}}
 [period,division,state].forEach(x=>x.addEventListener('change',()=>load()));window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);period.value=q.get('period')||period.value;division.value=q.get('division')||'all';state.value=q.get('state')||'open';load(false)});render(currentData);
});
</script>
@endpush
