@extends('layouts.executive-center')
@section('title','Strategic Reports')
@section('page_title','Strategic Reports')
@section('page_description','Management evaluation snapshots, strategic decisions, and action plans by period.')

@section('header_actions')
<button id="openGenerateReport" type="button" class="h-10 rounded-xl bg-executive-primary px-4 text-xs font-extrabold text-white shadow-button transition hover:bg-executive-primaryDark">Generate Report</button>
@endsection

@push('styles')
<style>.executive-main-card{overflow:visible!important;border:0!important;background:transparent!important;box-shadow:none!important}.executive-page-header{border:1px solid #E5E1EE!important;border-radius:1.25rem!important;background:#fff!important;box-shadow:0 16px 45px rgba(31,27,46,.07)!important}.executive-content{padding-right:0!important;padding-bottom:0!important;padding-left:0!important}@media(max-width:639px){.executive-page-header{border-radius:1rem!important}}</style>
@endpush

@section('content')
<div id="reportLibraryPage" class="relative min-w-0" aria-busy="false">
<div id="reportLibraryLoading" class="absolute inset-0 z-20 hidden min-h-[360px] items-start justify-center rounded-2xl bg-white/90 pt-20" role="status"><div class="text-center"><svg class="mx-auto h-7 w-7 animate-spin text-executive-primary" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-opacity=".2" stroke-width="3"/><path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" stroke-width="3"/></svg><p class="mt-3 text-sm font-extrabold">Loading strategic reports...</p></div></div>
<form id="reportLibraryFilters" method="GET" class="grid gap-3 rounded-2xl border border-executive-line bg-white p-4 shadow-panel sm:grid-cols-2 xl:grid-cols-4">
<select name="type" class="h-10 rounded-xl border border-executive-line px-3 text-xs font-bold"><option value="">All report types</option><option value="monthly" @selected(($filters['type']??'')==='monthly')>Monthly</option><option value="quarterly" @selected(($filters['type']??'')==='quarterly')>Quarterly</option></select>
<select name="year" class="h-10 rounded-xl border border-executive-line px-3 text-xs font-bold"><option value="">All years</option>@foreach($years as $year)<option value="{{ $year }}" @selected(($filters['year']??'')==$year)>{{ $year }}</option>@endforeach</select>
<select name="status" class="h-10 rounded-xl border border-executive-line px-3 text-xs font-bold"><option value="">All statuses</option><option value="draft" @selected(($filters['status']??'')==='draft')>Draft</option><option value="finalized" @selected(($filters['status']??'')==='finalized')>Finalized</option></select>
<input name="search" value="{{ $filters['search']??'' }}" placeholder="Search reports" class="h-10 rounded-xl border border-executive-line px-3 text-xs font-bold">
</form>
<div id="reportLibraryContent" class="mt-5">
@if($reports->isEmpty())<div class="rounded-2xl border border-dashed border-executive-line bg-white px-6 py-16 text-center"><h2 class="text-sm font-extrabold text-executive-ink">No strategic reports yet</h2><p class="mt-2 text-xs text-executive-muted">Generate the first monthly or quarterly management snapshot.</p></div>
@else<div class="grid gap-4 lg:grid-cols-2">@foreach($reports as $report)<article class="rounded-2xl border border-executive-line bg-white p-5 shadow-panel"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-[10px] font-bold uppercase text-executive-primary">{{ ucfirst($report->period_type) }} · Revision {{ $report->revision }}</p><h2 class="mt-2 text-sm font-extrabold text-executive-ink">{{ $report->title }}</h2><p class="mt-1 text-xs text-executive-muted">{{ $report->period_start->format('d M Y') }} – {{ $report->period_end->format('d M Y') }}</p></div><span class="rounded-md px-2.5 py-1 text-[9px] font-extrabold uppercase ring-1 ring-inset {{ $report->status==='finalized'?'bg-emerald-50 text-emerald-700 ring-emerald-200':'bg-amber-50 text-amber-700 ring-amber-200' }}">{{ ucfirst($report->status) }}</span></div><dl class="mt-5 grid grid-cols-2 gap-3 text-[10px]"><div><dt class="text-executive-muted">Business Health</dt><dd class="mt-1 font-extrabold text-executive-ink">{{ ucfirst(str_replace('_',' ',$report->overall_business_health??'Data Limited')) }}</dd></div><div><dt class="text-executive-muted">Data Confidence</dt><dd class="mt-1 font-extrabold text-executive-ink">{{ ucfirst($report->data_confidence??'Unavailable') }} · {{ $report->data_coverage??0 }}%</dd></div><div><dt class="text-executive-muted">Generated</dt><dd class="mt-1 font-extrabold text-executive-ink">{{ $report->generated_at?->format('d M Y H:i')??'—' }}</dd></div><div><dt class="text-executive-muted">Finalized</dt><dd class="mt-1 font-extrabold text-executive-ink">{{ $report->finalized_at?->format('d M Y H:i')??'—' }}</dd></div></dl><div class="mt-5 flex flex-wrap gap-2"><a href="{{ route('executive-center.strategic-reports.show',$report) }}" class="rounded-xl bg-executive-primary px-4 py-2 text-[10px] font-extrabold text-white">View Report</a><a href="{{ route('executive-center.strategic-reports.pdf',$report) }}" class="rounded-xl border border-executive-line px-4 py-2 text-[10px] font-extrabold text-executive-primary">Export PDF</a></div></article>@endforeach</div><div class="mt-5">{{ $reports->links() }}</div>@endif
</div></div>

<div id="generateReportDialog" class="fixed inset-0 z-[80] hidden items-center justify-center bg-slate-950/30 p-4"><form id="generateReportForm" action="{{ route('executive-center.strategic-reports.store') }}" method="POST" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-shell">@csrf<h2 class="text-lg font-extrabold text-executive-ink">Generate Strategic Report</h2><p class="mt-1 text-xs text-executive-muted">Create or refresh a Draft snapshot.</p><label class="mt-5 block text-xs font-bold">Report type<select name="period_type" class="mt-2 h-11 w-full rounded-xl border border-executive-line px-3"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></label><label class="mt-4 block text-xs font-bold">Period<input name="period" type="month" value="{{ now()->format('Y-m') }}" class="mt-2 h-11 w-full rounded-xl border border-executive-line px-3"></label><div id="generateReportStatus" class="mt-4 hidden rounded-xl bg-violet-50 p-3 text-xs text-executive-primary">FlexOps is consolidating KPI, academic, and source freshness data. This may take a moment.</div><div class="mt-6 flex justify-end gap-2"><button type="button" id="closeGenerateReport" class="rounded-xl border border-executive-line px-4 py-2 text-xs font-bold">Cancel</button><button type="submit" class="rounded-xl bg-executive-primary px-4 py-2 text-xs font-extrabold text-white">Generate</button></div></form></div>
@endsection

@push('scripts')<script>
document.addEventListener('DOMContentLoaded',()=>{const filters=document.getElementById('reportLibraryFilters'),page=document.getElementById('reportLibraryPage'),loading=document.getElementById('reportLibraryLoading');let c=null,t=null;async function load(){c?.abort();c=new AbortController();page.setAttribute('aria-busy','true');loading.classList.remove('hidden');loading.classList.add('flex');const url=`${location.pathname}?${new URLSearchParams(new FormData(filters))}`;try{const r=await fetch(url,{signal:c.signal,headers:{'X-Requested-With':'XMLHttpRequest'}});const d=new DOMParser().parseFromString(await r.text(),'text/html');document.getElementById('reportLibraryContent').replaceWith(d.getElementById('reportLibraryContent'));history.pushState({},'',url)}finally{if(!c.signal.aborted){page.setAttribute('aria-busy','false');loading.classList.add('hidden');loading.classList.remove('flex')}}}filters.querySelectorAll('select').forEach(x=>x.addEventListener('change',load));filters.search.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(load,350)});const dialog=document.getElementById('generateReportDialog');document.getElementById('openGenerateReport').onclick=()=>{dialog.classList.remove('hidden');dialog.classList.add('flex')};document.getElementById('closeGenerateReport').onclick=()=>{dialog.classList.add('hidden');dialog.classList.remove('flex')};document.getElementById('generateReportForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=document.getElementById('generateReportStatus'),buttons=form.querySelectorAll('button,select,input'),csrf=document.querySelector('meta[name="csrf-token"]')?.content||form.elements._token?.value||'',action=new URL(form.action,location.href),payload=new FormData(form);buttons.forEach(x=>x.disabled=true);status.classList.remove('hidden');try{const r=await fetch(`${action.pathname}${action.search}`,{method:'POST',body:payload,credentials:'same-origin',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest','X-CSRF-TOKEN':csrf}});const p=await r.json();if(!r.ok)throw new Error(p.message||'Report generation failed.');location.href=p.redirect}catch(error){status.textContent=error.message;status.classList.add('text-rose-700')}finally{buttons.forEach(x=>x.disabled=false)}});});
</script>@endpush
