<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:28px}body{font-family:DejaVu Sans,sans-serif;color:#2D2938;font-size:9px}h1{color:#5B3E8E;font-size:20px;margin:0}h2{font-size:13px;color:#5B3E8E;border-bottom:1px solid #E5E1EE;padding-bottom:5px;margin-top:20px}.meta{color:#737082;margin-top:6px}.box{border:1px solid #E5E1EE;border-radius:6px;padding:10px;margin:7px 0}.grid{width:100%;border-collapse:collapse}.grid th,.grid td{border:1px solid #E5E1EE;padding:6px;text-align:left;vertical-align:top}.grid th{background:#F8F5FC;color:#5B3E8E}.badge{font-weight:bold}.muted{color:#737082}.page-break{page-break-before:always}</style></head><body>
<h1>{{ $report->title }}</h1><p class="meta">{{ ucfirst($report->period_type) }} · {{ $report->period_start->format('d M Y') }} – {{ $report->period_end->format('d M Y') }} · Revision {{ $report->revision }} · {{ ucfirst($report->status) }}</p>
<h2>Executive Summary</h2><div class="box">{{ $report->executive_summary }}</div><table class="grid"><tr><th>Business Health</th><th>Data Confidence</th><th>Coverage</th></tr><tr><td>{{ ucfirst(str_replace('_',' ',$report->overall_business_health)) }}</td><td>{{ ucfirst($report->data_confidence) }}</td><td>{{ $report->data_coverage }}%</td></tr></table>
<h2>Strategic KPI Overview</h2><table class="grid"><thead><tr><th>KPI</th><th>Actual</th><th>Previous</th><th>Target</th><th>Status</th><th>Source</th></tr></thead><tbody>@foreach($report->kpi_snapshot??[] as $kpi)<tr><td>{{ $kpi['label'] }}</td><td>{{ $kpi['actual_formatted'] }}</td><td>{{ $kpi['previous_actual']??'—' }}</td><td>{{ $kpi['target_formatted'] }}</td><td>{{ $kpi['status_label'] }}</td><td>{{ $kpi['source'] }}</td></tr>@endforeach</tbody></table>
<h2>Centre Performance</h2><table class="grid"><thead><tr><th>Centre</th><th>Health</th><th>Summary</th><th>Main Issue</th></tr></thead><tbody>@foreach($report->centre_performance_snapshot??[] as $centre)<tr><td>{{ $centre['name'] }}</td><td>{{ $centre['status_label'] }}</td><td>{{ $centre['kpi_summary']??'—' }}</td><td>{{ $centre['main_issue']??'—' }}</td></tr>@endforeach</tbody></table>
<h2>Cross-Functional Analysis</h2><table class="grid"><tr>@foreach($report->cross_functional_snapshot??[] as $metric)<td><b>{{ $metric['label'] }}</b><br>{{ $metric['formatted'] }}</td>@if($loop->iteration%3===0)</tr><tr>@endif @endforeach</tr></table>
<div class="page-break"></div><h2>Strategic Wins, Risks, and Opportunities</h2>@foreach([['Wins',$report->wins],['Risks',$report->risks],['Opportunities',$report->opportunities]] as [$title,$items])<h3>{{ $title }}</h3>@forelse($items??[] as $item)<div class="box"><b>{{ $item['title']??'Insight' }}</b><br><span class="muted">{{ $item['description']??$item['evidence']??'' }}</span></div>@empty<p class="muted">Not Available</p>@endforelse @endforeach
<h2>Management Decisions</h2><table class="grid"><tr><th>Decision</th><th>Reason</th><th>Expected Impact</th><th>Centre</th><th>Priority</th></tr>@foreach($report->management_decisions??[] as $row)<tr><td>{{ $row['action']??'—' }}</td><td>{{ $row['reason']??'—' }}</td><td>{{ $row['expected_impact']??'—' }}</td><td>{{ $row['centre']??'—' }}</td><td>{{ $row['priority']??'—' }}</td></tr>@endforeach</table>
<h2>Strategic Action Plan</h2><table class="grid"><tr><th>Action</th><th>Centre</th><th>PIC</th><th>Deadline</th><th>Priority</th><th>Status</th></tr>@foreach($report->action_plan??[] as $row)<tr><td>{{ $row['action'] }}</td><td>{{ $row['centre'] }}</td><td>{{ $row['pic'] }}</td><td>{{ $row['deadline'] }}</td><td>{{ $row['priority'] }}</td><td>{{ $row['status'] }}</td></tr>@endforeach</table>
<h2>Data Confidence</h2><p>Coverage {{ $report->data_coverage }}% · Confidence {{ ucfirst($report->data_confidence) }}</p>@foreach($report->source_limitations??[] as $limit)<div class="box"><b>{{ $limit['source'] }}</b><br>{{ $limit['message'] }}</div>@endforeach
</body></html>
